# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/server/
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d

workflows:
  version: 2
  release-build:
    jobs:
      - release:
          filters:
            branches:
              only:
                - /release\/.*/
      
      - hold-push-tag:
          type: approval
          requires:
            - release
